Repository virtualescapes/company-escape, pull requests merged in 2020-06, with the labels that each got.

#5 Desktop login
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/assets/desktop-pb.jpg
  client/src/components/Desktop/DesktopLogin.js
  client/src/components/FullWrapper.js
  client/src/stories/0-DesktopLogin.stories.js
  client/src/stories/0-Welcome.stories.js
  client/src/stories/1-Button.stories.js
  package-lock.json
  package.json
  server.js
Labels: design

#7 Add GlobalStyles
  client/.storybook/ThemeDecorator.js
  client/.storybook/config.js
  client/src/App.js
  client/src/themes/GlobalStyles.js
Labels: storybook, styled-components

#11 Create Note and Add it to storybook
  client/src/components/Note.js
  client/src/stories/Note.stories.js
Labels: frontend, storybook, styled-components

#14 Create puzzle
  client/src/assets/puzzle-pieces/1.png
  client/src/assets/puzzle-pieces/10.png
  client/src/assets/puzzle-pieces/11.png
  client/src/assets/puzzle-pieces/12.png
  client/src/assets/puzzle-pieces/13.png
  client/src/assets/puzzle-pieces/14.png
  client/src/assets/puzzle-pieces/15.png
  client/src/assets/puzzle-pieces/16.png
  client/src/assets/puzzle-pieces/2.png
  client/src/assets/puzzle-pieces/3.png
  client/src/assets/puzzle-pieces/4.png
  client/src/assets/puzzle-pieces/5.png
  client/src/assets/puzzle-pieces/6.png
  client/src/assets/puzzle-pieces/7.png
  client/src/assets/puzzle-pieces/8.png
  client/src/assets/puzzle-pieces/9.png
  client/src/components/Puzzle/Countdown.js
  client/src/components/Puzzle/Puzzle.js
  client/src/stories/Countdown.stories.js
  client/src/stories/Puzzle.stories.js
  package-lock.json
  package.json
Labels: frontend, storybook

#15 Add social media chat
  .eslintrc.js
  client/src/components/Desktop/social-media/Chat.js
  client/src/components/ThoughtBubble.js
  client/src/stories/ChatSteffi.stories.js
  client/src/stories/ThoughtBubble.stories.js
  package-lock.json
  package.json
Labels: frontend, storybook, styled-components

#29 Add finsta chat modal
  client/src/assets/social-media/closeModal.svg
  client/src/components/Desktop/social-media/Chat.js
  client/src/components/Desktop/social-media/Finstagram.js
  client/src/components/Desktop/social-media/FinstagramHeader.js
  client/src/components/Desktop/social-media/FinstagramModal.js
  client/src/components/contexts/FinstagramChatModalContext.js
  client/src/stories/FinstagramModal.stories.js
Labels: frontend

#32 Fixes
  client/src/components/Desktop/social-media/FinstagramHeader.js
  client/src/components/Desktop/social-media/FinstagramPostModal.js
  client/src/stories/FinstagramModal.stories.js
Labels: fix
