Repository virtualescapes/company-escape, pull requests merged in 2020-07, with the labels that each got.

#34 Add paper component for documents
  client/public/index.html
  client/src/assets/paper-coffee.jpg
  client/src/assets/paper1.jpg
  client/src/assets/paper2.jpg
  client/src/components/documents/Paper.js
  client/src/stories/Documents.stories.js
Labels: frontend

#35 Create group chat
  client/src/assets/mobile/checks.svg
  client/src/assets/mobile/email-pattern-custom.png
  client/src/assets/mobile/mockup.svg
  client/src/assets/mobile/party.jpg
  client/src/components/mobile/WhatsUp.js
  client/src/stories/WhatsUp.stories.js
Labels: frontend, storybook, styled-components

#37 Add apartment pictures
  client/src/assets/apartment/container_nah.jpg
  client/src/assets/apartment/container_nah2.jpg
  client/src/assets/apartment/dunstabzug_nah.jpg
  client/src/assets/apartment/dunstabzug_nah_hoch.jpg
  client/src/assets/apartment/esstisch_nah.jpg
  client/src/assets/apartment/küche.jpg
  client/src/assets/apartment/papierkorb_nah.jpg
  client/src/assets/apartment/regal_nah.jpg
  client/src/assets/apartment/schreibtisch_nah.jpg
  client/src/assets/apartment/tafel_nah.jpg
  client/src/assets/apartment/tafel_nah2.jpg
  client/src/assets/apartment/wohnzimmer.jpg
Labels: design

#39 Add react router
  client/src/App.js
Labels: react

#40 Add kitchen to apartment
  client/src/App.js
  client/src/assets/apartment/esstisch_nah_kleiner.jpg
  client/src/assets/apartment/kueche.jpg
  client/src/assets/apartment/kueche_kleiner.jpg
  client/src/assets/foot.svg
  client/src/assets/mobile/smartphone-mockup.png
  client/src/components/Footprint.js
  client/src/components/contexts/WhatsUpModalContext.js
  client/src/components/mobile/WhatsUp.js
  client/src/pages/Esstisch.js
  client/src/pages/Kueche.js
  client/src/pages/Wohnzimmer.js
Labels: design, react context
